### ISSUE TITLE
Only 131 weights loaded

### ISSUE THREAD

**Issue by DominikVincent** [OxWearables/ssl-wearables#19]
Hello,

I am running this code to load the model:

`import torch
repo = 'OxWearables/ssl-wearables'
harnet = torch.hub.load(repo, "harnet30", class_num=5, pretrained=True)`

However, it returns while saying: 131 Weights loaded
This seems odd to me as the network has a few million.

Happens on: python3.8 with pytorch 2.1.2 and pytorch 1.11

**Comment by chanshing** [comment]
I think that's the number of layers or modules rather than number of params. Can you try the following instead?

```python
model = torch.hub.load(...)
total_params = sum(p.numel() for p in model.parameters())
print(f"Total Parameters in Model: {total_params}")
```

**Comment by DominikVincent** [comment]
You are correct. 

the printing is incorrect when the model is loaded. It shows the number of layer that are loaded.

See hubconf.py line 40-41

If you replace that by 

```
    model.load_state_dict(model_dict)
    # count the number of weights that are loaded
    sum_weights = sum([tens.numel() for tens in pretrained_dict.values()])
    print("%d Layers loaded, %d total weights loaded" % (len(pretrained_dict), sum_weights))
```

it shows that the weights are indeed loaded correctly.
```
import torch repo = 'OxWearables/ssl-wearables' 
harnet = torch.hub.load(repo, "harnet30", class_num=5, pretrained=True)
> 131 Layers loaded, 4241877 total weights loaded
```
