### ISSUE TITLE
How should I get Rowlands datasets?

### ISSUE THREAD

**Issue by Sample-design-alt** [OxWearables/ssl-wearables#26]
Thanks for your great work! 
But how should I get the Rowlands datasets? As you mentioned, `The Rowlands dataset can be requested by contacting Alex Rowlands
directly'..

**Comment by chanshing** [comment]
Hi @Sample-design-alt 
The Rowlands dataset is not publicly available so you'll need to ask Alex Rowlands:
https://le.ac.uk/people/alex-rowlands
