### ISSUE TITLE
Mismatch between provided labels in Capture-24 and published figures? 

### ISSUE THREAD

**Issue by findalexli** [OxWearables/ssl-wearables#9]
Hello authors, 

I saw that using your processed capture 24_30hz_full Y.npy, the unique labels are 
{'moderate-vigorous', 'sleep', 'light', 'sedentary'}
However, I was confused when I see the corresponding UMAP feature map in the paper. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/11794421/232375665-cb861b5d-1c58-4879-8033-272680403f24.png">
Can you please explain the difference? 

As a side question, with all due respect why was the subset of labels chosen out of the annotation directory, dubbed Walmsley2020? They seem to be easy to be distinguished by the the magnitude of accelerator along and does not carry any periodic information or fine upper body activity.

**Comment by angerhang** [comment]
The dataset description paper has been published here: https://arxiv.org/abs/2402.19229

Hopefully that should clarify this issue, hence closing.
